#!/bin/bash

err () { printf "pmake: %s\n" "$*" 1>&1; exit 2; }

# make wrapper for paris
test "$PARIS_PREFIX" || err "PARIS_PREFIX is not set"
test "$PARIS_BIN"    || err "PARIS_BIN is not set"

: ${MAKE:=make}
"${MAKE}" \
    HAVE_VOFI=1 HAVE_SILO=1 \
    SILO_DIR="$PARIS_PREFIX/silo" \
    HYPRE_DIR="$PARIS_PREFIX/hypre/lib" \
    VOFI_DIR="$PARIS_PREFIX/vofi/lib" \
    BINDIR="$PARIS_BIN" \
    FLAGS="-O3 -cpp  -fimplicit-none" \
    "$@"

# I have to overwrite FLAGS becouse gfortran 4.8.5 does not recognize
# -ffpe-summary

